### ISSUE TITLE
unable to use px-buttons-design..

### ISSUE THREAD

**Issue by Aanchal25** [PredixDev/px-buttons-design#2]
steps followed:
1. bower install px-buttons-design --save
2.@import "px-buttons-design/_objects.buttons.scss"; in the px-buttons-design/src/style.scss file.
3.Did $inuit-enable-btn--primary: true !default; in the _object.buttons.scss file of px-buttons-design.

Still btn--primary class is  not getting applied.Please help

**Comment by arcpato** [comment]
the @import and the enabling to true have to be done in your application's scss, not on the px-buttons-design files. You should not be modifying the bower components files.
